### ISSUE TITLE
Readme

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/news_server_py#2]
Хорошая документация получилась. Небольшие изменения, которые порекомендовала бы сделать:

- добавить про то, что запускается фикстура при старте докер-компоуз (для тестирования админки надо знать логин и пароль, а для публичного запуска надо знать это, чтобы поменять пароль на более сложный) 
- If you change the parameters in `.env` make sure that the `Dockerfile` and `docker-compose.yml` files are also changed - кажется в докерфайле/докер-копоузе не надо ничего менять при изменении значений переменных окружения, т.к. енв подружается из файла.

**Comment by paffel2** [comment]
Это относится к портам. Если вдруг захотят пробросить порты на другие, то нужно docker-compose редактировать.

**Comment by olgaklimenko** [comment]
Ага, для портов нужно, да) тогда оставляем, или уточнить можно, что про порты речь )

**Comment by paffel2** [comment]
Лучше уточню
