### ISSUE TITLE
Permission class

### ISSUE THREAD

**Issue by olgaklimenko** [paffel2/news_server_py#3]
Можно сделать [кастомный Permission class](https://www.django-rest-framework.org/api-guide/permissions/#custom-permissions) и использовать в списке `permission_classes` для вьюхи. Такой пермишен можно переиспользовать и не обрабатывать вручную ошибку доступа.
(Увидела это в AuthorsAPIView, там нужно разрешить POST запрос только админам)

**Comment by paffel2** [comment]
Я когда дошел декораторов, думал лучше переделать с ними. Но хорошо гляну.
